services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - common-net

  metastore-db:
    image: postgres:15-alpine
    container_name: metastore-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_DB: metastore
    ports:
      - "5432:5432"
    volumes:
      - metastore-db:/var/lib/postgresql/data
    networks:
      - common-net

  hive-metastore:
    build:
      context: ./docker/hive
      dockerfile: Dockerfile
    image: my-hive
    container_name: hive-metastore
    restart: unless-stopped
    depends_on:
      - metastore-db
      - minio
      - minio-init
    ports:
      - "9083:9083"
    networks:
      - common-net

  trino:
    image: trinodb/trino:476
    container_name: trino
    restart: unless-stopped
    depends_on:
      - hive-metastore
      - minio
    ports:
      - "8080:8080"
    volumes:
      - ./docker/trino/etc:/etc/trino
      - ./docker/init/lakehouse_init.sql:/init/lakehouse_init.sql
    networks:
      - common-net

  minio-init:
    image: python:3.10-bullseye
    container_name: minio-init
    restart: "no"
    depends_on:
      - minio
    volumes:
      - ./docker/init/minio_init.py:/init/minio_init.py
    command: >
      /bin/sh -c "pip install --no-cache-dir minio && python /init/minio_init.py"
    networks:
      - common-net

volumes:
  minio-data:
    name: minio-data
  metastore-db:
    name: metastore-db

networks:
  common-net:
    external: true
